// Mock seed data for the blog
import type { Post, Category, Author } from "./types";

export const seedAuthor: Author = {
  id: "ddumba-ak",
  username: "ddumba",
  password: "ddumba2025", // demo only — frontend simulation
  name: "Ddumba AK",
  fullName: "Abdallah Kato Ddumba",
  role: "Platform & AI Systems Engineer",
  tagline: "Architecting LLM Infrastructure at Scale | AWS, Kubernetes, RAG, & Inference Optimization",
  location: "Kampala, Central Region, Uganda",
  avatar: "/profile.png",
  bio: `AI Platform Engineer | Production AI & Infrastructure

I build the "Engines" that allow AI to survive in production.

While much of the industry is focused on prompt engineering, I focus on the "Day 2" reality: Why is the inference cost higher than projected? Why is the RAG pipeline latency lagging? How do we scale a Kubernetes cluster to handle tens of thousands of concurrent agentic requests?

I sit at the intersection of Platform Reliability and AI System Design. My goal is to transform "Experimental AI" into "Enterprise-Grade Infrastructure" that is resilient, observable, and profitable.`,
  challenges: [
    "AI systems that work in dev but fail to scale under production loads",
    "High inference costs without a clear optimization strategy",
    "Latency and observability gaps in complex RAG pipelines",
    "Infrastructure bottlenecks when deploying GPU-intensive workloads",
  ],
  focusAreas: [
    "AI Infrastructure",
    "Inference Optimization",
    "RAG Systems",
    "AWS",
    "Kubernetes",
    "Terraform",
    "ArgoCD",
    "vLLM",
    "TensorRT-LLM",
  ],
  techStack: [
    "LangChain", "LlamaIndex", "PyTorch", "Pinecone", "AWS",
    "Kubernetes", "Kafka", "Terraform", "Grafana", "Prometheus",
  ],
  contacts: {
    linkedin: "https://linkedin.com/in/ddumbaka",
    twitter: "",
    facebook: "",
    whatsapp: "",
    companyWebsite: "https://kyakabi.com",
    personalWebsite: "https://ddumba.kyakabi.com",
    phone: "+256701019242",
    email: "abdallahddumbakato@gmail.com",
  },
};

export const seedCategories: Category[] = [
  { slug: "ai-infrastructure", name: "AI Infrastructure", color: "from-emerald-400 to-teal-500" },
  { slug: "rag-systems", name: "RAG Systems", color: "from-cyan-400 to-blue-500" },
  { slug: "kubernetes", name: "Kubernetes", color: "from-violet-400 to-indigo-500" },
  { slug: "inference", name: "Inference", color: "from-amber-400 to-orange-500" },
  { slug: "platform", name: "Platform Engineering", color: "from-pink-400 to-rose-500" },
  { slug: "observability", name: "Observability", color: "from-lime-400 to-green-500" },
];

const lorem = (h: string, body: string) => ({
  type: "section" as const, heading: h, body,
});

export const seedPosts: Post[] = [
  {
    id: "p1",
    slug: "scaling-llm-inference-vllm-kubernetes",
    title: "Scaling LLM Inference: vLLM on Kubernetes at 10K Concurrent Requests",
    excerpt: "How we redesigned our inference plane using vLLM, KServe, and a custom autoscaler to serve tens of thousands of concurrent agentic requests without burning cash.",
    coverImage: "",
    coverGradient: "linear-gradient(135deg,#0f3,#0aa,#06f)",
    category: "inference",
    tags: ["vLLM", "Kubernetes", "KServe", "GPU"],
    authorId: "ddumba-ak",
    publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
    readingTime: 12,
    status: "published",
    featured: true,
    trending: true,
    views: 12480,
    seo: { title: "Scaling LLM Inference with vLLM", description: "Production patterns for vLLM on Kubernetes." },
    content: [
      { type: "paragraph", text: "Production AI is not a prompt — it is a distributed system. When the marketing team launches at 9 AM, your GPU fleet either holds the line or melts. This essay is the playbook we wish we had." },
      { type: "heading", level: 2, text: "Why vLLM Wins" },
      { type: "paragraph", text: "PagedAttention turns the KV cache from a static reservation into a virtual memory manager. The result is 3-5x throughput on the same hardware." },
      { type: "list", ordered: false, items: ["Continuous batching out of the box", "Tensor and pipeline parallel support", "OpenAI-compatible server"] },
      { type: "code", language: "yaml", code: "apiVersion: serving.kserve.io/v1beta1\nkind: InferenceService\nmetadata:\n  name: llama-70b\nspec:\n  predictor:\n    model:\n      runtime: vllm\n      storageUri: s3://models/llama-3-70b" },
      { type: "quote", text: "If you can't observe it, you can't scale it. Period.", cite: "Ddumba AK" },
      { type: "heading", level: 2, text: "The Autoscaler" },
      { type: "paragraph", text: "HPA on CPU is useless for GPU workloads. We built a custom KEDA scaler that reads queue depth from vLLM's /metrics endpoint and scales replicas based on p99 token latency." },
    ],
    comments: [],
  },
  {
    id: "p2",
    slug: "rag-pipeline-latency-budget",
    title: "Anatomy of a RAG Pipeline: Building a 200ms p99 Latency Budget",
    excerpt: "Vector DB tuning, query rewriting, hybrid search, and the art of caching embeddings — a complete latency teardown.",
    coverImage: "",
    coverGradient: "linear-gradient(135deg,#f0f,#a0f,#60a)",
    category: "rag-systems",
    tags: ["RAG", "Pinecone", "LangChain", "Latency"],
    authorId: "ddumba-ak",
    publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
    readingTime: 9,
    status: "published",
    featured: false,
    trending: true,
    views: 8930,
    seo: { title: "RAG Latency Budget", description: "Engineer a 200ms p99 RAG pipeline." },
    content: [
      { type: "paragraph", text: "Every millisecond of RAG latency is paid by your user. Here is how we shaved 1.4 seconds off our pipeline." },
      { type: "heading", level: 2, text: "The Stages" },
      { type: "list", ordered: true, items: ["Query rewriting (LLM)", "Embedding (cached)", "Vector search (hybrid)", "Rerank", "Context assembly", "Generation"] },
    ],
    comments: [],
  },
  {
    id: "p3",
    slug: "terraform-modules-gpu-clusters",
    title: "Terraform Modules for GPU-Native EKS Clusters",
    excerpt: "A reusable module set for spinning up A100/H100 clusters with NVIDIA Operator, MIG partitioning, and spot resilience.",
    coverImage: "",
    coverGradient: "linear-gradient(135deg,#fa0,#f60,#a30)",
    category: "ai-infrastructure",
    tags: ["Terraform", "EKS", "GPU", "AWS"],
    authorId: "ddumba-ak",
    publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 8).toISOString(),
    readingTime: 7,
    status: "published",
    featured: false,
    trending: true,
    views: 5620,
    seo: { title: "Terraform GPU EKS", description: "GPU EKS modules for AI workloads." },
    content: [{ type: "paragraph", text: "Infrastructure as code for the AI era." }],
    comments: [],
  },
  {
    id: "p4",
    slug: "observability-llm-pipelines-grafana",
    title: "LLM Observability: Tracing Token Streams Across Grafana & Prometheus",
    excerpt: "The metrics, dashboards, and alerts that let us catch model degradation before users do.",
    coverImage: "",
    coverGradient: "linear-gradient(135deg,#0af,#06f,#03a)",
    category: "observability",
    tags: ["Grafana", "Prometheus", "Tracing"],
    authorId: "ddumba-ak",
    publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 12).toISOString(),
    readingTime: 8,
    status: "published",
    featured: false,
    trending: false,
    views: 4310,
    seo: { title: "LLM Observability", description: "Observe LLM pipelines properly." },
    content: [{ type: "paragraph", text: "You cannot scale what you cannot see." }],
    comments: [],
  },
  {
    id: "p5",
    slug: "argocd-gitops-ml-platforms",
    title: "GitOps for ML Platforms: ArgoCD Patterns That Actually Work",
    excerpt: "Multi-tenant model serving via ArgoCD ApplicationSets, with progressive rollouts and automated rollback.",
    coverImage: "",
    coverGradient: "linear-gradient(135deg,#3f3,#0a3,#063)",
    category: "platform",
    tags: ["ArgoCD", "GitOps", "ML"],
    authorId: "ddumba-ak",
    publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 18).toISOString(),
    readingTime: 10,
    status: "published",
    featured: false,
    trending: false,
    views: 3104,
    seo: { title: "ArgoCD ML", description: "GitOps for ML." },
    content: [{ type: "paragraph", text: "GitOps is the only way to keep ML platforms sane." }],
    comments: [],
  },
  {
    id: "p6",
    slug: "kafka-event-driven-agents",
    title: "Event-Driven Agents: Kafka as the Nervous System of Multi-Agent Systems",
    excerpt: "Why we abandoned synchronous agent orchestration for an event log — and how it 10x'd throughput.",
    coverImage: "",
    coverGradient: "linear-gradient(135deg,#f3a,#a3f,#63f)",
    category: "ai-infrastructure",
    tags: ["Kafka", "Agents", "Events"],
    authorId: "ddumba-ak",
    publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 22).toISOString(),
    readingTime: 11,
    status: "published",
    featured: false,
    trending: true,
    views: 2890,
    seo: { title: "Kafka Agents", description: "Event-driven agentic systems." },
    content: [{ type: "paragraph", text: "Async beats sync at scale, every single time." }],
    comments: [],
  },
  {
    id: "p7",
    slug: "tensorrt-llm-cost-optimization",
    title: "TensorRT-LLM in Production: Cutting Inference Cost by 60%",
    excerpt: "Quantization, speculative decoding, and the engineering tradeoffs nobody talks about.",
    coverImage: "",
    coverGradient: "linear-gradient(135deg,#0fa,#0c8,#085)",
    category: "inference",
    tags: ["TensorRT-LLM", "Quantization", "Cost"],
    authorId: "ddumba-ak",
    publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 26).toISOString(),
    readingTime: 13,
    status: "published",
    featured: false,
    trending: false,
    views: 2210,
    seo: { title: "TensorRT-LLM Cost", description: "Cost-optimal inference with TRT-LLM." },
    content: [{ type: "paragraph", text: "FP8, INT4, speculative decoding — pick your poison." }],
    comments: [],
  },
  {
    id: "p8",
    slug: "pinecone-vs-weaviate-2025",
    title: "Pinecone vs Weaviate vs pgvector: A 2025 Production Bake-Off",
    excerpt: "Hard numbers on recall, latency, cost-per-query, and operational burden across three popular vector stores.",
    coverImage: "",
    coverGradient: "linear-gradient(135deg,#0ff,#0aa,#077)",
    category: "rag-systems",
    tags: ["Pinecone", "Weaviate", "pgvector"],
    authorId: "ddumba-ak",
    publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 30).toISOString(),
    readingTime: 14,
    status: "published",
    featured: false,
    trending: false,
    views: 1980,
    seo: { title: "Vector DB Bakeoff", description: "Vector DB comparison 2025." },
    content: [{ type: "paragraph", text: "There is no universal winner — there is only fitness for your workload." }],
    comments: [],
  },
];

void lorem;
